/// Merging into a dataset the app did not create.
///
/// The failure this guards is silent: `buildBidsDataset` regenerates
/// `participants.tsv` with one column and rewrites `dataset_description.json`,
/// so a naive merge deletes the study's demographics and its DOI and still
/// produces valid BIDS that passes the validator. The fixture here carries
/// exactly the columns and keys a real dataset would, and the test asserts they
/// survive.
library;

import 'package:dbs_annotator/core/bids_dataset.dart';
import 'package:dbs_annotator/core/bids_merge.dart';
import 'package:dbs_annotator/core/tsv.dart';
import 'package:flutter_test/flutter_test.dart';

const _sessionTsv = 'acq_time\tblock_id\n2026-02-03T09:00:00+00:00\t1\n';
const _visitPath =
    'sub-01/ses-20260203/beh/sub-01_ses-20260203_task-programming_run-01_beh.tsv';
const _scansPath = 'sub-01/ses-20260203/sub-01_ses-20260203_scans.tsv';

/// A dataset as a lab would actually keep it: extra participant columns, a
/// curated description, and a subject this app has never seen.
List<DatasetFile> _curated() => [
  (
    path: 'dataset_description.json',
    content:
        '{"Name": "OCD DBS cohort", "Authors": ["Poma L"], '
        '"License": "CC0", "DatasetDOI": "doi:10.5281/zenodo.1234567"}',
  ),
  (path: 'README', content: 'Curated by hand. Do not overwrite.'),
  (
    path: 'participants.tsv',
    content: writeTsvRecords(
      const ['participant_id', 'age', 'sex', 'group'],
      const [
        {'participant_id': 'sub-01', 'age': '54', 'sex': 'F', 'group': 'OCD'},
        {'participant_id': 'sub-09', 'age': '61', 'sex': 'M', 'group': 'PD'},
      ],
    ),
  ),
  (
    path: _scansPath,
    content: writeTsvRecords(
      const ['filename', 'acq_time'],
      const [
        {
          'filename': 'beh/sub-01_ses-20260203_task-programming_run-01_beh.tsv',
          'acq_time': '2026-02-03T09:00:00+00:00',
        },
      ],
    ),
  ),
  (path: _visitPath, content: _sessionTsv),
  // Things the app knows nothing about, which must simply stay put.
  (
    path: 'sub-01/ses-20260203/anat/sub-01_ses-20260203_T1w.json',
    content: '{}',
  ),
  (path: 'derivatives/leaddbs/README', content: 'localisation outputs'),
];

/// A new visit for a new subject, as `buildBidsDataset` would emit it.
List<DatasetFile> _newVisit() => [
  (
    path: 'dataset_description.json',
    content: '{"Name": "DBS programming sessions"}',
  ),
  (path: 'README', content: 'Generated by DBS Annotator.'),
  (
    path: 'participants.tsv',
    content: writeTsvRecords(
      const ['participant_id'],
      const [
        {'participant_id': 'sub-01'},
        {'participant_id': 'sub-42'},
      ],
    ),
  ),
  (
    path: 'sub-42/ses-20260310/sub-42_ses-20260310_scans.tsv',
    content: writeTsvRecords(
      const ['filename', 'acq_time'],
      const [
        {
          'filename': 'beh/sub-42_ses-20260310_task-programming_run-01_beh.tsv',
          'acq_time': '2026-03-10T10:00:00+00:00',
        },
      ],
    ),
  ),
  (
    path:
        'sub-42/ses-20260310/beh/sub-42_ses-20260310_task-programming_run-01_beh.tsv',
    content: 'acq_time\tblock_id\n2026-03-10T10:00:00+00:00\t1\n',
  ),
];

Map<String, String> _written(MergePlan plan) => {
  for (final f in plan.write) f.path: f.content,
};

void main() {
  test('the curated description and README are never rewritten', () {
    final plan = planBidsMerge(_curated(), _newVisit());
    expect(_written(plan).containsKey('dataset_description.json'), isFalse);
    expect(_written(plan).containsKey('README'), isFalse);
    expect(plan.keptAsIs, contains('dataset_description.json'));
    expect(plan.keptAsIs, contains('README'));
  });

  test('participants.tsv keeps every column and every existing row', () {
    final plan = planBidsMerge(_curated(), _newVisit());
    final merged = _written(plan)['participants.tsv'];
    expect(merged, isNotNull, reason: 'it gains a subject, so it is rewritten');

    final rows = parseTsvRecords(merged!);
    expect(rows.map((r) => r['participant_id']), [
      'sub-01',
      'sub-09',
      'sub-42',
    ]);
    // The demographics are the thing a naive merge destroys.
    expect(rows[0]['age'], '54');
    expect(rows[0]['sex'], 'F');
    expect(rows[0]['group'], 'OCD');
    expect(rows[1]['participant_id'], 'sub-09', reason: 'an untouched subject');
    expect(rows[1]['group'], 'PD');
    // The new subject has no demographics yet, which is missing, not wrong.
    expect(rows[2]['age'], isEmpty);
  });

  test('a file the app does not own is never mentioned, so never touched', () {
    final plan = planBidsMerge(_curated(), _newVisit());
    final paths = plan.write.map((f) => f.path);
    expect(
      paths,
      isNot(contains('sub-01/ses-20260203/anat/sub-01_ses-20260203_T1w.json')),
    );
    expect(paths, isNot(contains('derivatives/leaddbs/README')));
  });

  test('the new visit and its scans.tsv are added', () {
    final plan = planBidsMerge(_curated(), _newVisit());
    expect(
      plan.added,
      containsAll([
        'sub-42/ses-20260310/beh/sub-42_ses-20260310_task-programming_run-01_beh.tsv',
        'sub-42/ses-20260310/sub-42_ses-20260310_scans.tsv',
      ]),
    );
  });

  test('an existing scans.tsv gains a row and keeps the one it had', () {
    final plan = planBidsMerge(_curated(), [
      (
        path: _scansPath,
        content: writeTsvRecords(
          const ['filename', 'acq_time'],
          const [
            {
              'filename':
                  'beh/sub-01_ses-20260203_task-programming_run-02_beh.tsv',
              'acq_time': '2026-02-03T11:00:00+00:00',
            },
          ],
        ),
      ),
    ]);
    final merged = parseTsvRecords(_written(plan)[_scansPath]!);
    expect(merged, hasLength(2));
    expect(merged.first['filename'], endsWith('run-01_beh.tsv'));
    expect(merged.last['filename'], endsWith('run-02_beh.tsv'));
  });

  test('recorded data at an existing path is refused, never overwritten', () {
    final plan = planBidsMerge(_curated(), const [
      (path: _visitPath, content: 'acq_time\tblock_id\nDIFFERENT\t9\n'),
    ]);
    expect(plan.refused, [_visitPath]);
    expect(_written(plan).containsKey(_visitPath), isFalse);
  });

  test('re-merging the same files changes nothing', () {
    final target = _curated();
    final once = planBidsMerge(target, _newVisit());
    final applied = [
      ...target.where((f) => !once.write.any((w) => w.path == f.path)),
      ...once.write,
    ];
    final twice = planBidsMerge(applied, _newVisit());
    expect(twice.write, isEmpty, reason: 'idempotent: nothing left to do');
    expect(twice.refused, isEmpty);
  });

  test('merging into an empty target writes the whole dataset', () {
    final plan = planBidsMerge(const [], _newVisit());
    expect(plan.write, hasLength(_newVisit().length));
    expect(plan.refused, isEmpty);
    expect(plan.keptAsIs, isEmpty);
  });

  test('the summary names what will happen', () {
    final text = describeMergePlan(planBidsMerge(_curated(), _newVisit()));
    expect(text, contains('added'));
    expect(text, contains('gaining rows'));
  });
}
